export const TYPE_ADD = 'TYPE_ADD'

// collection
export const COLLECTION_ADD = 'COLLECTION_ADD'
export const COLLECTION_EDIT = 'COLLECTION_EDIT'
export const COLLECTION_DEL = 'COLLECTION_DEL'
export const COLLECTION_BYID = 'COLLECTION_BYID'
export const COLLECTION_GET = 'COLLECTION_GET'

// matching
export const MATCHING_ADD = 'MATCHING_ADD'
export const MATCHING_EDIT = 'MATCHING_EDIT'
export const MATCHING_DEL = 'MATCHING_DEL'
export const MATCHING_BYID = 'MATCHING_BYID'
export const MATCHING_GET = 'MATCHING_GET'